NAME : PAREENITA A.SHIRSATH   ROLL.NO:49  B.E.A.I.&.D.S.

**AAI EXPERIMENT NO 1 : Design And Implement Hidden Markov Models for outcome prediction In Python**

In [2]:
!pip install hmmlearn
import numpy as np
from hmmlearn.hmm import MultinomialHMM
observations = np.array([
[0], [1], [2], [1], [0], [2], [2], [1], [0]
])
lengths = [len(observations)]
model = MultinomialHMM(
n_components=3,
n_iter=200,
random_state=42
)
model.fit(observations, lengths)
hidden_states = model.predict(observations)
print("Observed sequence:")
print(observations.flatten())
print("\nPredicted hidden states:")
print(hidden_states)
last_state = hidden_states[-1]
next_state_probabilities = model.transmat_[last_state]
predicted_next_state = np.argmax(next_state_probabilities)
print("\nTransition probabilities from last state:")
print(next_state_probabilities)
print("\nPredicted next hidden state:")
print(predicted_next_state)
# -----------------------------
# 6. Model Parameters
# -----------------------------
print("\nInitial state probabilities:")
print(model.startprob_)
print("\nTransition matrix:")
print(model.transmat_)
print("\nEmission matrix:")
print(model.emissionprob_)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 3.9 MB/s eta 0:00:00


https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


Observed sequence:
[0 1 2 1 0 2 2 1 0]

Predicted hidden states:
[1 0 1 0 1 0 1 0 1]

Transition probabilities from last state:
[0.95463874 0.00797929 0.03738197]

Predicted next hidden state:
0

Initial state probabilities:
[0.1140845  0.87766916 0.00824634]

Transition matrix:
[[9.01320140e-04 9.99058562e-01 4.01179591e-05]
 [9.54638745e-01 7.97928839e-03 3.73819670e-02]
 [4.02174984e-01 1.24429527e-01 4.73395489e-01]]

Emission matrix:
[[1.]
 [1.]
 [1.]]
